Add commons-codec library which is needed for PutHttpPassword
PutHttpPassword relies on org.apache.commons.codec.binary.Base64
without bringing the corresponding library into the set of
dependencies. Hence, building in-tree fails with

  [...]/plugins/serviceuser/[...]/PutHttpPassword.java:31: error: package org.apache.commons.codec.binary does not exist
  import org.apache.commons.codec.binary.Base64;
                                        ^

(see [1] and [2]). By adding the commons-codec dependency, the plugin
builds and loads again, when building in-tree.
(This change does not cover standalone build)

[1] http://builds.quelltextlich.at/gerrit/nightly/master/2015-06-25/serviceuser.jar.build.stderr.txt
[2] http://builds.quelltextlich.at/gerrit/nightly/master/2015-06-25/index.html#serviceuser.jar

Change-Id: Idf54d41ac8735665e77629abde9fc78881497f19