Update patch set 8
Patch Set 8:

> This no longer works.  The build fails with lots of errors,
 > starting with:
 > 
 > gerrit/plugins/serviceuser/src/main/java/com/googlesource/gerrit/plugins/serviceuser/client/ConfigInfo.java:17:
 > error: package com.google.gerrit.client.rpc does not exist
 > import com.google.gerrit.client.rpc.NativeMap;
 > 
 > The maven build still works.

That's because of two different bugs:

* gwtexpui dependency was added to pom.xml but not to BUCK
* after extracting of gerrit-gwtui-common out of gerrit-gwtui gerrit_plugin wasn't adjusted.

Will upload a fix in a minute.

Patch-set: 8