Update patch set 8
Patch Set 8:

This no longer works.  The build fails with lots of errors, starting with:

 gerrit/plugins/serviceuser/src/main/java/com/googlesource/gerrit/plugins/serviceuser/client/ConfigInfo.java:17: error: package com.google.gerrit.client.rpc does not exist
 import com.google.gerrit.client.rpc.NativeMap;

The maven build still works.

Patch-set: 8