Update patch set 1
Patch Set 1:

> Doesn't compile in standalone mode:
 > 
 > Compiling module com.googlesource.gerrit.plugins.serviceuser.CreateServiceUserForm
 > [ERROR] Unexpected internal compiler error
 > java.lang.NoClassDefFoundError: org/objectweb/asm/MethodVisitor
 > 
 > and I get the same when trying to build cookbook-plugin 2.11-rc0 in
 > standalone mode.

That's because asm was unbundled from gwt-dev.jar. This is explained in 2.7 migration change [1], and that why asm libs were explicitlly added in [2].

* [1] https://gerrit-review.googlesource.com/59353
* [2] https://gerrit-review.googlesource.com/#/c/59353/21/gerrit-gwtui/BUCK

Patch-set: 1
Label: Code-Review=0